### ISSUE TITLE
Packages not found in OpenSuse Dockerfile

### ISSUE THREAD

**Issue by David-Gil** [Wenzel/docker-kdesrc-build#1]
I have run the Opensuse Dockerfile and it fails to find the following packages:
- Package 'libQt5Script-devel' not found.
- Package 'docbook-style-xsl' not found.
- Package 'xcb-utils-keysyms-devel' not found.

I have also changed the OpenSuse Dockerfile to pull the 13.1 image. It fails to find the following packages:
- Package 'docbook-style-xsl' not found.
- Package 'xcb-utils-keysyms-devel' not found.

**Comment by Wenzel** [comment]
Hello, 
i switched this dockerfile to opensuse:13.1, and fixed the missing packages.
It should build fine now.
thanks for the report !

**Comment by David-Gil** [comment]
It builds ok!
