### ISSUE TITLE
Problem in Synchronizing package databases. 

### ISSUE THREAD

**Issue by dinosath** [Wenzel/docker-kdesrc-build#12]
when i run ./run.py --base archlinux
I get the following error 

error: failed retrieving file 'core.db' from mirrors.advancedhosters.com : Resolving timed out after 10519 milliseconds
error: failed retrieving file 'core.db' from arch.mirrors.ionfish.org : Resolving timed out after 10520 milliseconds
error: failed retrieving file 'core.db' from mirror.cc.columbia.edu : Resolving timed out after 10519 milliseconds
error: failed retrieving file 'core.db' from mirror.clibre.uqam.ca : Resolving timed out after 10520 milliseconds
error: failed retrieving file 'core.db' from mirror.metrocast.net : Resolving timed out after 10519 milliseconds
error: failed retrieving file 'core.db' from mirror.us.leaseweb.net : Resolving timed out after 10520 milliseconds
error: failed retrieving file 'core.db' from mirror.rit.edu : Resolving timed out after 10519 milliseconds
error: failed retrieving file 'core.db' from mirror.yellowfiber.net : Resolving timed out after 10520 milliseconds
error: failed retrieving file 'core.db' from mirror.vtti.vt.edu : Resolving timed out after 10520 milliseconds
error: failed retrieving file 'core.db' from mirror.es.its.nyu.edu : Resolving timed out after 10520 milliseconds

**Comment by Wenzel** [comment]
Hi !
It seems that the container has no internet connection.
Can you check that you are able to get a netwok access inside a simple container with the following command :

```
$ docker run -ti ubuntu:latest ping www.google.com
```

**Comment by dinosath** [comment]
I also tried running the following: ./run.py --base ubuntu 
but it had errors with apt-get connecting to the internet

**Comment by dinosath** [comment]
Yeah i found out that the problem was with docker. So i tried the following
service docker restart
