### ISSUE TITLE
Permissions problem with docker user in ubuntu-kdedev

### ISSUE THREAD

**Issue by David-Gil** [Wenzel/docker-kdesrc-build#3]
Hi!

In a Ubuntu-kdedev container I try to clone the kdesrc-build repository and I get the following message.

root@cf8a98f89f0a:/work# su docker
docker@cf8a98f89f0a:/work$ git clone git://anongit.kde.org/kdesrc-build.git
fatal: could not create work tree dir 'kdesrc-build'.: Permission denied

The thing is I don't understand why there has to be a docker user. It is not that I disagree with it being created, it is that I don't know enough.

**Comment by Wenzel** [comment]
Hi,
did you bind /work on a directory on your host system ?
Maybe you need to run `chown docker:users` -R again in the container to r/w permissions.

I can't remember why i needed the docker user.
When I started this project a month ago, i had an issue regarding the root user, so I had to create a simple user account.

I have removed the `docker` user from the Dockerfiles.
Can you test with this configuration please ?

**Comment by David-Gil** [comment]
I briefly tested that configuration and kdesrc-build didn't work. It stayed in the first lines. I'd need more time, because I don't have any 64-bit computer at home. Next week I'll try changing the /work folder owner (I didn't bind the folder to the host machine to make things simpler). Maybe I'll find out what happens.
